version: '3'
services:
  notebook:
    container_name: Jupyter_Scipy
    image: jupyter/scipy-notebook
    #build: .
    #  context: ./scienceData
    ports: 
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
      
    volumes:
      - ./files:/home/jovyan/work 
    hostname: localhost